### ISSUE TITLE
Random hard client crash

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#14]
**Describe the bug**
Had a few times now. Client just suddenly instantly crashes

**To Reproduce**
Nothing much. Just walking around. Not in combat. Not clicking. 

**Crash Log or Latest.log**
[Render thread/ERROR] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 8193
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.rehash(Long2ReferenceOpenHashMap.java:1334) ~[fastutil-8.5.6.jar%2330!/:?] {}
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.insert(Long2ReferenceOpenHashMap.java:279) ~[fastutil-8.5.6.jar%2330!/:?] {}
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.put(Long2ReferenceOpenHashMap.java:287) ~[fastutil-8.5.6.jar%2330!/:?] {}
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.createSection(ClonedChunkSectionCache.java:49) ~[rubidium-0.5.2a.jar%23228!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.acquire(ClonedChunkSectionCache.java:27) ~[rubidium-0.5.2a.jar%23228!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.WorldSlice.prepare(WorldSlice.java:126) ~[rubidium-0.5.2a.jar%23228!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.createRebuildTask(RenderSectionManager.java:380) ~[rubidium-0.5.2a.jar%23228!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterfpsdist.mixins.json:Sodiummixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.submitRebuildTasks(RenderSectionManager.java:347) ~[rubidium-0.5.2a.jar%23228!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterfpsdist.mixins.json:Sodiummixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:314) ~[rubidium-0.5.2a.jar%23228!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterfpsdist.mixins.json:Sodiummixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197) ~[rubidium-0.5.2a.jar%23228!/:?] {re:mixin,re:classloading,pl:mixin:APP:rubidium_extras.mixins.json:fog.MixinSodiumWorldRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:9628) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:scannable:Render Scan Effect,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:scannable:Render Scan Effect,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1156) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:scannable:Render Scan Effect,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:scannable:Render Scan Effect,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23274!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.52.jar%2350!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?] {}

**Comment by Saereth** [comment]
https://github.com/Saereth/inferno_issues/issues/1
